In [22]:
#Import
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import flopy
import flopy.modflow as mf
import flopy.mt3d as mt
import flopy.utils as fu

In [23]:
#MODFLOW 2005
modelname = 'example'
mf_model = mf.Modflow(modelname = modelname, exe_name='mf2005.exe')

In [24]:
#DIS file
Lx = 310
Ly = 310
nrow = 31
ncol = 31
nlay = 1
delr = Lx / ncol
delc = Ly / nrow
top = np.ones((nrow, ncol))
botm = np.zeros((nrow, ncol))
perlen = 27

dis = mf.ModflowDis(mf_model, nlay, nrow, ncol, delr = delr, delc = delc, 
                    top = top, botm = botm, laycbd = 0, itmuni=4, perlen = perlen, 
                    nstp = 1)

In [25]:
# Output Control: Create a flopy output control object
oc = mf.ModflowOc(mf_model)

In [26]:
#BCF file
laycon=0 #confined
tran=1.0 #transmissivity
bcf = flopy.modflow.mfbcf.ModflowBcf(mf_model,laycon=0, tran=1.0)

In [27]:
#BAS file
ibound = np.ones((nlay, nrow, ncol)) #active
ibound[0, 0, :31] = -1 #constant head
ibound[0, 30, :31] = -1
ibound[0, :31, 0] = -1
ibound[0, :31, 30] = -1

strt=15 #starting head
ibound

array([[[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1., -1., -1., -1., -1.],
        [-1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1., -1.],
        [-1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1., -1.],
        [-1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1., -1.],
        [-1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1.,  1.,  1.,  1.,  1., -1.],
        [-1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1.,  1

In [28]:
bas = mf.ModflowBas(mf_model, ibound = ibound, strt = strt)

In [29]:
#PCG file
pcg = flopy.modflow.mfpcg.ModflowPcg(mf_model, mxiter=20, iter1=30, hclose=1e-03, rclose=1e-03, relax=1.0)

In [30]:
#CHD
#[lay, row, col, shead, ehead]

chd=15
chd_data = []
for c in range(30):
    dd = np.array([0, 0, c, chd, chd])
    chd_data.append(dd)
for c in range(31):
    dd = np.array([0, c, 30, chd, chd])
    chd_data.append(dd)
for c in range(30):
    dd = np.array([0, 30, c, chd, chd])
    chd_data.append(dd)
for c in range(1,30):
    dd = np.array([0, c, 0, chd, chd])
    chd_data.append(dd)
stress_period_data = {0:chd_data}

stress_period_data

{0: [array([ 0,  0,  0, 15, 15]),
  array([ 0,  0,  1, 15, 15]),
  array([ 0,  0,  2, 15, 15]),
  array([ 0,  0,  3, 15, 15]),
  array([ 0,  0,  4, 15, 15]),
  array([ 0,  0,  5, 15, 15]),
  array([ 0,  0,  6, 15, 15]),
  array([ 0,  0,  7, 15, 15]),
  array([ 0,  0,  8, 15, 15]),
  array([ 0,  0,  9, 15, 15]),
  array([ 0,  0, 10, 15, 15]),
  array([ 0,  0, 11, 15, 15]),
  array([ 0,  0, 12, 15, 15]),
  array([ 0,  0, 13, 15, 15]),
  array([ 0,  0, 14, 15, 15]),
  array([ 0,  0, 15, 15, 15]),
  array([ 0,  0, 16, 15, 15]),
  array([ 0,  0, 17, 15, 15]),
  array([ 0,  0, 18, 15, 15]),
  array([ 0,  0, 19, 15, 15]),
  array([ 0,  0, 20, 15, 15]),
  array([ 0,  0, 21, 15, 15]),
  array([ 0,  0, 22, 15, 15]),
  array([ 0,  0, 23, 15, 15]),
  array([ 0,  0, 24, 15, 15]),
  array([ 0,  0, 25, 15, 15]),
  array([ 0,  0, 26, 15, 15]),
  array([ 0,  0, 27, 15, 15]),
  array([ 0,  0, 28, 15, 15]),
  array([ 0,  0, 29, 15, 15]),
  array([ 0,  0, 30, 15, 15]),
  array([ 0,  1, 30, 15, 15]),
  arr